[build]
  functions = "netlify/functions"
  publish = "public"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = ":splat"
  status = 200
  force = true

[[redirects]]
  from = "/form/*"
  to = "/form/:splat"
  status = 200
  force = true